sudo: false
language: python
python:
  - 2.7
  - 3.6
  - pypy
  - pypy3
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/pip install -e .
script:
- bin/python setup.py test
- bin/i18ndude find-untranslated src/i18ndude/tests/input/test1.pt
- bin/i18ndude find-untranslated src/i18ndude/tests || echo 'find-untranslated is expected to give errors for missing translations'
